version: '3'
services:
  node-app:
    build: .
    image: app2/nodejs:v3
    env_file:
      - /.env
    ports:
      - "${PORT}"
  nginx:
    build: ./nginx
    image: app2/nginx:v3
    ports:
      - "${EXPORT}:3008"
    depends_on:
      - node-app